@startuml

class Topic {
    long TopicId
    string Name
    datetime Created
    datetime Updated
}

class Comment {
	long CommentId
    long TopicId
	string Source
	string Username
    string Content
    datetime Created
}


@enduml
