@startuml

class Topic {
    long topic_id
    string name

    init(name string): Topic
}

class Comment {
	long comment_id
    long topic_id
	string source
	string username
    string content

    init(topic_id: long, source: string, username: string, content: string): Comment
}

Topic "1" -- "n" Comment


@enduml
